### ISSUE TITLE
Mean value is not ms but 1/ 10 sec

### ISSUE THREAD

**Issue by sittingbool** [mtkennerly/kelonio#10]
Hi, I am running requests against a mongodb and meassuring with kelonio:

```
const measurement = await measure(() => {
  const promises: Promise<SessionRecord | null>[] = [];
  do {
      const token = TestDataSessions['user1'].tokens[0];
      promises.push(Database.getSession(token));
      numberOfUsers--;
  } while (numberOfUsers > 0);
  return Promise.all(promises);
});
return measurement.mean;
```
This process takes about 2 sec. Which I can clearly see. So I used the test run feature of Webstorm which also measures. But measurement.mean returns exactly 100th of that value. If I multiply measurement.mean with 100 the value fits (WebStorm returns a few ms more because of the test framework overhead of course). 

example values:
mean 8.39 vs Webstorm 854 ms
mean 22.34 vs Webstorm 2340 ms

I can see on the test-run that this test takes 1-2sec and also using breakpoints around the measured function it takes clearly that long and not just 8-22ms.

**Comment by mtkennerly** [comment]
Hi! If you're running the exact same Kelonio code through WebStorm, then that's weird, but `measure()` defaults to 100 iterations ([docs](https://mtkennerly.github.io/kelonio/interfaces/measureoptions.html#iterations)), so that's why the total time would be 100x an individual measurement. You can see it more clearly if you set only 1 iteration. Here's a test that explicitly lasts for 2,000 ms:

```
    it("reports in ms", async () => {
        const m = await measure(
            () => new Promise(resolve => setTimeout(resolve, 2_000)),
            { iterations: 1 }
        );
        console.log(`mean: ${m.mean} ms`);
    });
```

And the associated logging:

```
  console.log
    mean: 2001.6599 ms
```

Could you confirm that you're running the exact same Kelonio code in WebStorm (and not running the measured function on its own without Kelonio)?

**Comment by sittingbool** [comment]
Thank you that explains a lot! It might be good to point out the default documentation on top of the README file where you give the example or explain the behavior there more directly ;) 
You can close this then. Setting to one iteration worked out for me.
